// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TaskForceCMDContext))]
    partial class TaskForceCMDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.DataModel.CollaboratorDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Collaborator");
                });

            modelBuilder.Entity("Infrastructure.DataModel.ProjectDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Infrastructure.DataModel.SubjectDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("Infrastructure.DataModel.TaskForceCollaboratorDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskForceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TaskForceCollaborator");
                });

            modelBuilder.Entity("Infrastructure.DataModel.TaskForceDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TaskForce", (string)null);
                });

            modelBuilder.Entity("Infrastructure.DataModel.TaskForceDataModel", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("TaskForceDataModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Description");

                            b1.HasKey("TaskForceDataModelId");

                            b1.ToTable("TaskForce");

                            b1.WithOwner()
                                .HasForeignKey("TaskForceDataModelId");
                        });

                    b.OwnsOne("Domain.ValueObjects.PeriodDate", "PeriodDate", b1 =>
                        {
                            b1.Property<Guid>("TaskForceDataModelId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("EndDate");

                            b1.Property<DateOnly>("InitDate")
                                .HasColumnType("date")
                                .HasColumnName("InitDate");

                            b1.HasKey("TaskForceDataModelId");

                            b1.ToTable("TaskForce");

                            b1.WithOwner()
                                .HasForeignKey("TaskForceDataModelId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("PeriodDate")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
